store-after/config/routes.rb
Store::Application.routes.draw do
  resources :products
  root to: 'products#index'
end

store-after/app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :name, :price, :released_on, :category
end

store-after/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    respond_to do |format|
      format.html
      format.json { render json: ProductsDatatable.new(view_context) }
    end
  end

  def show
    @product = Product.find(params[:id])
  end
end

store-after/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Store</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, id: "flash_#{name}" %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

store-after/app/views/products/index.html.erb
<h1>Products</h1>

<table id="products" class="display" data-source="<%= products_url(format: "json") %>">
  <thead>
    <tr>
      <th>Product Name</th>
      <th>Category</th>
      <th>Release Date</th>
      <th>Price</th>
    </tr>
  </thead>
  <tbody>
  </tbody>
</table>

store-after/app/views/products/show.html.erb
<h1><%= @product.name %></h1>

<p>
  <b>Price:</b>
  <%= number_to_currency @product.price %>
</p>

<p>
  <b>Released on:</b>
  <%= @product.released_on.strftime("%B %e, %Y") %>
</p>

<p>
  <b>Category:</b>
  <%= @product.category.name %>
</p>

<%= link_to 'Back', products_path %>